### ISSUE TITLE
"ImportError: No module named 'requests'" on install

### ISSUE THREAD

**Issue by justanr** [ablator/karman#6]
To reproduce: Create a new Python 3 venv and do not allow system site packages, run `pip install karman`.

The issue is that the `setup.py` imports the module it wants to install, however that module imports a dependency that has not been installed yet. 

Solutions:

* Do not import the `karman` module into `setup.py` and instead use a tool like bumpversion to manage versions.

* Use a regex to find and parse the version number from the text of the `karman.version` module

* Maintain the version number in both the `setup.py` AND `karman.version`

Additionally, publishing a wheel would put a bandage over this issue and allow end users to install.

**Comment by winsmith** [comment]
Oops, thanks for noticing, and especially thanks for the fix suggestions!
